version: '3.8'

services:
  web:
    build: .
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=uploads
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
