# Generated by Django 3.1.3 on 2020-11-14 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveIntegerField()),
                ('product_name', models.CharField(max_length=64)),
                ('product_quantity', models.PositiveIntegerField()),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='upload_server.upload')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
